export const iconList = [
  { title: "Arrow Right", value: "ArrowRight" },
  { title: "Award", value: "Award" },
  { title: "Balance Scale", value: "Scale" },
  { title: "Bank / Landmark", value: "Landmark" },
  { title: "Bar Chart", value: "BarChart3" },
  { title: "Book Open", value: "BookOpen" },
  { title: "Briefcase", value: "Briefcase" },
  { title: "Building", value: "Building" },
  { title: "Building 2", value: "Building2" },
  { title: "Calculator", value: "Calculator" },
  { title: "Check Circle", value: "CheckCircle" },
  { title: "Coins", value: "Coins" },
  { title: "Compass", value: "Compass" },
  { title: "Credit Card", value: "CreditCard" },
  { title: "Database", value: "Database" },
  { title: "Dollar Sign", value: "DollarSign" },
  { title: "Edit", value: "Edit" },
  { title: "External Link", value: "ExternalLink" },
  { title: "Eye", value: "Eye" },
  { title: "File Text", value: "FileText" },
  { title: "Filter", value: "Filter" },
  { title: "Flag", value: "Flag" },
  { title: "Folder", value: "Folder" },
  { title: "Globe", value: "Globe" },
  { title: "Growth / Trending Up", value: "TrendingUp" },
  { title: "Handshake", value: "Handshake" },
  { title: "Heart", value: "Heart" },
  { title: "Help Circle", value: "HelpCircle" },
  { title: "Home", value: "Home" },
  { title: "Key", value: "Key" },
  { title: "Layers", value: "Layers" },
  { title: "Line Chart", value: "LineChart" },
  { title: "Lock", value: "Lock" },
  { title: "Mail", value: "Mail" },
  { title: "Map", value: "Map" },
  { title: "Map Pin", value: "MapPin" },
  { title: "Network", value: "Network" },
  { title: "Package", value: "Package" },
  { title: "Palette", value: "Palette" },
  { title: "Phone", value: "Phone" },
  { title: "Pie Chart", value: "PieChart" },
  { title: "Plane", value: "Plane" },
  { title: "Rocket", value: "Rocket" },
  { title: "Scale", value: "Scale" },
  { title: "Search", value: "Search" },
  { title: "Settings", value: "Settings" },
  { title: "Shield Check", value: "ShieldCheck" },
  { title: "Shopping Bag", value: "ShoppingBag" },
  { title: "Star", value: "Star" },
  { title: "Target", value: "Target" },
  { title: "Users", value: "Users" },
  { title: "Wallet", value: "Wallet" },
  { title: "Zap", value: "Zap" },
];
